implement ListOps.filter
rchain/rchain pull request #2581
Opened 2019-07-05 12:58 UTC by odeac

## Overview
see title

### JIRA ticket:
None

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

2019-07-05 13:56 UTC, JosephDenman requested changes
You have debugging leftovers. Otherwise, LGTM.

2019-07-05 13:56 UTC, JosDenmark commented on casper/src/main/resources/ListOps.rho
> +    new reverseCh, accumulate, stdout(`rho:io:stdout`) in {
Stdout

2019-07-05 14:15 UTC, odeac commented on casper/src/main/resources/ListOps.rho
> +    new reverseCh, accumulate, stdout(`rho:io:stdout`) in {
the horror!!!!!

2019-07-05 14:17 UTC, JosephDenman approved these changes

2019-07-08 10:46 UTC, KentShikama approved these changes

2019-07-08 11:13 UTC, odeac commented
bors r+

2019-07-08 12:02 UTC, merged