RCHAIN-3643 introduce key in pyrchain
rchain/rchain pull request #2598
Opened 2019-07-17 13:06 UTC by zsluedem

## Overview
introduce key in pyrchain

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3643

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

2019-07-17 13:06 UTC, zsluedem commented
bors try

2019-07-17 13:36 UTC, adaszko requested changes

2019-07-17 13:36 UTC, adaszko commented on integration-tests/test/test_wallets.py
> +        alice_rev_address = get_rev_address_by_public_key(context, started_standalone_bootstrap_node, ALICE_KEY.get_public_key().to_hex(), ALICE_KEY.to_hex())
The `.to_hex()` method should be called right before interpolating the key into a string, not before passing it as a parameter.  Functions like `get_rev_address_by_public_key()` should accept the `PrivateKey` type, not `str`.

2019-07-17 13:37 UTC, adaszko commented on integration-tests/Pipfile
> +pyrchain = {git = "https://github.com/rchain/pyrchain.git"}
Good idea 👍

2019-07-17 13:51 UTC, adaszko commented
Is the public key derived from the private key now?

2019-07-17 13:52 UTC, woky commented
> Is the public key derived from the private key now?

Correct. (`get_public_key()`)

2019-07-17 14:33 UTC, zsluedem commented
bors try

2019-07-17 16:17 UTC, adaszko requested changes

2019-07-17 16:17 UTC, adaszko commented on integration-tests/test/test_dag_correctness.py
> +                        deploy1 = DeployThread("validator1", validator1, contract_path, 10, BONDED_VALIDATOR_KEY_1.to_hex())
Same here

2019-07-17 16:17 UTC, adaszko commented on integration-tests/test/test_propose.py
> +    started_standalone_bootstrap_node.deploy(full_path, DEPLOY_KEY.to_hex())
and here

2019-07-17 16:17 UTC, adaszko commented on integration-tests/test/test_slash.py
> +            validator1.deploy(contract, BONDED_VALIDATOR_KEY_1.to_hex())
and here

2019-07-17 21:33 UTC, KentShikama commented
This should make https://github.com/rchain/rchain/pull/2476 pass right?

2019-07-18 01:12 UTC, zsluedem commented
bors try

2019-07-18 01:30 UTC, zsluedem commented
> This should make #2476 pass right?

I don't think so. All the tests related to `deploy and propose` fail in that pr.

2019-07-18 02:01 UTC, KentShikama commented
@zsluedem Nvm, I confused this PR with a ticket that would sign deploys in integration tests.

`INFO     root:rnode.py:287 rchain-gcjpe.bootstrap: Failure! Invalid block: DeployNotSigned`

2019-07-18 02:02 UTC, KentShikama commented
@zsluedem Is sign deploys used in integration tests somewhere on your TODO list though?

2019-07-18 02:55 UTC, zsluedem commented
> @zsluedem Is signing deploys used in integration tests somewhere on your TODO list though?

I think https://github.com/rchain/pyrchain/blob/master/rchain/util.py#L18-L38 is something you said.

2019-07-18 09:14 UTC, woky commented
> > @zsluedem Is signing deploys used in integration tests somewhere on your TODO list though?
> 
> I think https://github.com/rchain/pyrchain/blob/master/rchain/util.py#L18-L38 is something you said.

Yeah, if int. tests switch to Pyrchain and use `rclient.deploy(...)`, deploys should be signed.

2019-07-18 10:14 UTC, zsluedem commented
@adaszko updated~!

2019-07-18 14:08 UTC, adaszko requested changes

2019-07-18 14:08 UTC, adaszko commented on integration-tests/test/test_dag_correctness.py
> +                        deploy1 = DeployThread("validator1", validator1, contract_path, 10, BONDED_VALIDATOR_KEY_1.to_hex())
Can you make `DeployThread.__init__()` take `PrivateKey` type and not `str`?

2019-07-18 15:15 UTC, adaszko approved these changes

2019-07-18 16:39 UTC, woky approved these changes

2019-07-18 16:40 UTC, zsluedem commented
bors r+

2019-07-19 01:02 UTC, zsluedem commented
bors r+

2019-07-19 01:51 UTC, merged