Add test that simulates 16k vault creations + transfers
rchain/rchain pull request #2617
Opened 2019-07-24 08:54 UTC by KentShikama

## Overview
<sup>_What this PR does, and why it's needed_</sup>

Note this is just for @JosDenmark @ArturGajowy and anyone else who is investigating the full genesis ceremony execution. This test is a simplified version of the full genesis ceremony execution that brings forth all of the main issues: how to get 16k vault creations + transfers done in a reasonable amount of time.

### JIRA ticket:
<sup>_Create it if there isn't one already._</sup>

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

2019-07-24 09:53 UTC, ArturGajowy requested changes
There's no way we're merging this with the 300k lines of code that could be generated on the fly

2019-07-24 09:54 UTC, KentShikama commented
If it wasn't clear, this is not meant to be merged

2019-07-25 07:52 UTC, ArturGajowy commented on models/src/main/scala/coop/rchain/models/rholang/sorter/ExprSortMatcher.scala
> +        ScoredTerm(e, Node(Score.EBYTEARR, Leaf(Base16.encode(ba.toByteArray)))).pure[F]
base16.encode is a hellishly slow way to sort. We should rather use the byte array directly in the leaf, nad make sure that we sort Leaf(byteArray) using the array elements

2019-07-25 07:54 UTC, ArturGajowy commented on models/src/main/scala/coop/rchain/models/SortedParMap.scala
> -  def contains(par: Par): Boolean = sortedMap.contains(sort(par))
as mentioned in discord, lookups would be more efficient if we kept both a hashmap and a treemap, and did the lookups inside the hashMap

2019-07-25 13:12 UTC, JosDenmark commented on models/src/main/scala/coop/rchain/models/SortedParMap.scala
> +  @SuppressWarnings(Array("org.wartremover.warts.Var", "org.wartremover.warts.Null"))
@ArturGajowy @KentShikama This is why I used `TreeMap[ScoredTerm[Par], Par]`. No cache, no resorting.

2019-10-09 07:07 UTC, closed without merging