RCHAIN-3265 add bonding test again
rchain/rchain pull request #2686
Opened 2019-08-26 07:52 UTC by zsluedem

## Overview
<sup>_What this PR does, and why it's needed_</sup>

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3265

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

2019-08-26 07:53 UTC, zsluedem commented
bors try

2019-08-26 15:19 UTC, woky approved these changes
Python looks good

2019-08-27 12:05 UTC, zsluedem commented
@adaszko one more

2019-08-27 12:19 UTC, adaszko requested changes

2019-08-27 12:19 UTC, adaszko commented on integration-tests/test/test_heterogenous_validators.py
> +READONLY_PEER_KEY = PrivateKey.generate()
It looks like this introduces a source of non-determinism in the test.  Non-determinism causes flaky tests.  We should avoid it.  Is it possible to seed the underlying random number generator?

2019-08-27 12:47 UTC, adaszko approved these changes

2019-08-27 13:37 UTC, zsluedem commented
bors r+

2019-08-27 15:58 UTC, merged