Develop a way for RNode operators to learn about the bond status of a node
rchain/rchain pull request #2738
Opened 2019-09-20 02:46 UTC by itegulov

## Overview
Adds a command `rnode bond-status <publickey>` for checking whether a given validator is bonded or not in the last finalized block.

### JIRA ticket:
https://rchain.atlassian.net/browse/RCHAIN-3066

### Notes
<sup>_Optional. Add any notes on caveats, approaches you tried that didn't work, or anything else._</sup>

### Please make sure that this PR:
- [x] is at most 200 lines of code (excluding tests),
- [x] meets [RChain development coding standards](https://rchain.atlassian.net/wiki/spaces/DOC/pages/28082177/Coding+Standards),
- [x] includes tests for all added features,
- [x] has a reviewer assigned,
- [x] has [all commits signed](https://rchain.atlassian.net/wiki/spaces/DOC/pages/498630673/How+to+sign+commits+to+rchain+rchain).

### [Bors](https://bors.tech/) cheat-sheet:

- `bors r+` runs integration tests and merges the PR (if it's approved),
- `bors try` runs integration tests for the PR,
- `bors delegate+` enables non-maintainer PR authors to run the above.

2019-10-04 14:10 UTC, odeac requested changes

2019-10-04 14:10 UTC, odeac commented on casper/src/test/scala/coop/rchain/casper/api/BondedStatusAPITest.scala
> +}
We are missing a test showing that bondStatus returns false for a validator that is bonded in a block which is not yet finalized

2019-10-08 07:00 UTC, itegulov commented
@odeac PTAL

2019-10-08 07:26 UTC, KentShikama approved these changes

2019-10-08 07:26 UTC, KentShikama commented on casper/src/main/scala/coop/rchain/casper/api/BlockAPI.scala
> +      publicKey: ByteString
Is this a private key, public key, validator identity, etc? I believe we have specific types for each one.

2019-10-09 11:29 UTC, odeac approved these changes

2019-10-09 22:07 UTC, itegulov commented
bors r+

2019-10-10 02:22 UTC, itegulov commented
bors r+

2019-10-10 03:35 UTC, merged